name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:25.0.0
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: rebar3 do dialyzer, ct
