name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['29', '28', '27']
        rebar3: ['3.27']
    runs-on: 'ubuntu-26.04'
    steps:
      - uses: actions/checkout@v7
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ${{ runner.os }}-otp-${{ steps.setup-beam.outputs.otp-version }}-rebar3-${{ steps.setup-beam.outputs.rebar3-version }}-${{ hashFiles('rebar.lock', 'rebar.config') }}
      - run: rebar3 compile
      - run: rebar3 check
