name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    name: Publish to Hex and create a GitHub release
    runs-on: 'ubuntu-26.04'
    steps:
      - uses: actions/checkout@v7
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '29'
          rebar3-version: '3.27'
      - run: rebar3 compile
      - name: Publish package and docs to Hex
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: rebar3 hex publish --yes
      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
